### ISSUE TITLE
MVP, Schema, and Sample State Review

### ISSUE THREAD

**Issue by vawhitehouse** [ChristopherCFleming/FauxFlix#1]
# MVP
- [x] #1 should be Hosting on Heroku (user auth can be moved to #2)
- [x] #2 is not necessary - this is already implied when creating a clone
- [ ] missing #7: Production README
- [x] add a rough estimated completion time for each (2-3 days for each one)
- User Auth (Account management)
  - [x] You don't need to worry about separate profiles within a single account
  - [x] be sure that this mvp includes creating a new account, loggin in, and having a demo login
  - [x] users must be logged in to browse, watch, create list, etc.
- Genres
  - [x] You also need to display videos based on their genre
- My List
  - [x] "Users Can Create Lists of Videos" -> a user can only create one list
  - [x] users can view, update, delete from their list
- I don't think ratings need to be factored in at all - it's not one of your mvps so you can remove any mention of ratings

# Schema
- [x] everything should be styled the same way as it would in the database - lower case, snake_case
- `users`
  - [x] `session_token` should be unique and indexed
  - [x] Will you need both `username` & `email`? or just one of them?
- `videos`
  - [x] I won't worry about a `match_percent` - this likely won't be something you implement (or you'll add it in later as a bonus MVP)
  - [x] You may want to make the data type for `description` be text rather than string (string is limited to 255 characters)
  - [x] You won't keep an array of genres on the video table (see not below on creating a joins table)
  - [x] An index on the `title` could be useful
- `list`
  - [x] You won't want to keep an individual `video_id`, since a list can have many videos (see note below on adding a joins table for this)
- [x] You'll need a `genres` table and a video/genre joins table that will keep track of the many-to-many relationship between videos and genres
- [x] `ratings` are not one of your MVPs so you won't need a table for it
- [x] You'll also want a joins table for videos in a user's list (each video can be in more than one user's list, and a list and can have many videos)

# Sample State
- [x] You should be adding a `genres` table so you would only want to keep an array of of `genreIds` in the `movies` slice of state
- [x] On that note, you'll also want a `genres` slice of state
- [x] can remove `match_percent` (same reasoning from schama note)
- [x] You'll want a `session` slice of state to keep track of the current user's id
